include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_generic_function_type_aliases
    - slash_for_doc_comments
    - unawaited_futures
    - unnecessary_const
    - unnecessary_new
